### ISSUE TITLE
Unable to map Guid to Guid?

### ISSUE THREAD

**Issue by AleyCZ** [PavelLev/MappingSourceGenerator#13]
This problem started to appear in version 0.1.9, it worked well in 0.1.8.

We have a class with a few properties and a constructor to initialize them. A few of these properties are Guid or Guid?.
Then we have the same class in a different namespace, but one parameter in the constructor is of type Guid? instead of Guid.
The library is unable to create the mapping method, we received this error message:
MAPGEN1030	Mapping for 'value' parameter of 'System.Nullable<T>' constructor is not found in type 'System.Guid'

I think when the value of T is always not-null (value types cannot be null), then it should always be possible to assign it to Nullable<T>.

**Comment by PavelLev** [comment]
Hi AleyCZ,

Thank you for using MappingSourceGenerator!

I've uploaded 0.1.10 version that should contain fix for the described issue. Also I've added tests to cover this functionality.

Please confirm that the issue is fixed for you

**Comment by AleyCZ** [comment]
Yes, my code does not compile with version 0.1.9, but compiles fine with 0.1.10. Thanks.
(I did not try to verify if the mapping is correct.)
